# Configuration for MCP Web Context
# Define model lists for each agent with fallback support

models:
  agents:
    web_content_analyzer:
      models:
        - provider: "openai"
          model: "gpt-5-mini"
          api_key_env: "OPENAI_API_KEY"
          temperature: 1
          reasoning:
            effort: "low"
            summary: null
        - provider: "ollama"
          model: "gemma3n"
          base_url: "http://localhost:11434"
          temperature: 0.5