# Configuration for MCP Web Context
# Define model lists for each agent with fallback support

models:
  agents:
    web_content_analyzer:
      models:
        - provider: "openai"
          model: "gpt-4o-mini"
          api_key_env: "OPENAI_API_KEY"
          temperature: 0.33
          reasoning:
            effort: "low"
            summary: null
        - provider: "openai"
          model: "gpt-4o"
          api_key_env: "OPENAI_API_KEY"
          temperature: 0.33
        - provider: "anthropic"
          model: "claude-3-haiku-20240307"
          api_key_env: "ANTHROPIC_API_KEY"
          temperature: 0.3
        - provider: "ollama"
          model: "llama3.2:3b"
          base_url: "http://localhost:11434"
          temperature: 0.3
          
    # Example for future agents
    # web_summarizer:
    #   models:
    #     - provider: "openai"
    #       model: "gpt-4o-mini"
    #       api_key_env: "OPENAI_API_KEY"
    #     - provider: "ollama"
    #       model: "llama3.2:1b"
    #       base_url: "http://localhost:11434"