# Configuration for MCP Web Context
# Define model lists for each agent with fallback support

models:
  agents:
    web_content_analyzer:
      models:
        - provider: "openai"
          model: "gpt-5-mini"
          api_key_env: "OPENAI_API_KEY"
          reasoning:
            effort: "low"
      
    research_agent:
      models:
        - provider: "openai"
          model: "gpt-5-mini"
          api_key_env: "OPENAI_API_KEY"
          reasoning:
            effort: "medium"
            summary: "auto"
