#!/bin/bash
# Simple floating terminal button

while true; do
    yad --button="Terminal:0" --button="Close:1" --title="Quick Access" --width=120 --height=80 --no-escape --skip-taskbar --on-top --undecorated --geometry=+10+10
    if [ $? -eq 0 ]; then
        alacritty &
    else
        break
    fi
done